<?xml version="1.0"?>
<robot name="llwrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="height" value="5"/>
    <xacro:property name="radius" value="1"/>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/llwrobot</robotNamespace>
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>
    </gazebo>
    <gazebo reference="link1">
      <material>Gazebo/Orange</material>
    </gazebo>
    <gazebo reference="link2">
      <material>Gazebo/Red</material>
    </gazebo>

    <link name="world"/>

    <joint name="fixed" type="fixed">
        <origin xyz="0 0 ${height/2}" rpy="0.0 0.0 0.0"/>   
        <parent link="world"/>
        <child link="link1"/>
        <dynamics damping="0.4"/>
    </joint>

    <link name="link1">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${radius}" length="${height}"/>
            </geometry> 
            <material name="yellow">
                <color rgba="1 0.4 0 1"/>  
            </material>
        </visual>

        <collision>
             <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${radius}" length="${height}"/>
            </geometry> 
        </collision>

        <inertial>
            <mass value="2"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>

    <joint name="joint1" type="continuous">
        <origin xyz="0 ${radius*2} ${height/2}" rpy="0.0 0.0 0.0"/>   
        <parent link="link1"/>
        <child link="link2"/>
        <axis xyz="0 1 0.0"/>
    </joint>

    <link name="link2">
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${radius}" length="${height}"/>
            </geometry> 
            <material name="yellow">
                <color rgba="1 0.4 0 1"/>  
            </material>
        </visual>

        <collision>
             <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <cylinder radius="${radius}" length="${height}"/>
            </geometry> 
        </collision>

        <inertial>
            <mass value="2"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.05" iyz="0.0" izz="0.0"/>
        </inertial>
    </link>


    <transmission name="tran1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor1">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
</robot>